name: Thaw
version: '${project.version}'
main: goat.thaw.Thaw
api-version: '1.21'
load: STARTUP
authors: [ DiscordGoat ]
description: A Frozen Survival Minecraft Project 
commands:
  generatearctic:
    description: Generate the Arctic dev world (void with vanilla bedrock)
    usage: /generatearctic
    permission: thaw.dev
    permission-message: You must be op to use this.
  warpto:
    description: Warp to another world/dimension by name
    usage: /warpto <worldname>
    permission: thaw.dev
    permission-message: You must be op to use this.
  decomission:
    description: Unload and delete the Arctic dev world
    usage: /decomission
    permission: thaw.dev
    permission-message: You must be op to use this.
  regeneratearctic:
    description: Decommission, regenerate, and warp to the Arctic dev world
    usage: /regeneratearctic
    permission: thaw.dev
    permission-message: You must be op to use this.
  teleporttopeak:
    description: Teleport to nearest terrain peak around you
    usage: /teleporttopeak [radius]
    permission: thaw.dev
    permission-message: You must be op to use this.
  statscommand:
    description: Dev stats command
    usage: /statscommand <get|set|add|subtract> <stat> [amount]
    permission: thaw.dev
    permission-message: You must be op to use this.
  spawntrailstart:
    description: Spawn a trail start under your feet
    usage: /spawntrailstart
    permission: thaw.dev
    permission-message: You must be op to use this.
  floodfillalgorithm:
    description: Dev DFS flood fill from one block above feet
    usage: /floodfillalgorithm [rate]
    permission: thaw.dev
    permission-message: You must be op to use this.
  externaltempdebug:
    description: Toggle external temperature drift debug actionbar
    usage: /externaltempdebug
    permission: thaw.dev
    permission-message: You must be op to use this.
  dicelog:
    description: Toggle DICE logging to file for your player
    usage: /dicelog
    permission: thaw.dev
    permission-message: You must be op to use this.
  sled:
    description: Dev SLED airboat
    usage: /sled
    permission: thaw.dev
    permission-message: You must be op to use this.
permissions:
  thaw.dev:
    description: Access to development commands
    default: op
